name: CI, Create PR, and Auto Merge

on:
  push:
    branches:
      - feature/*  # Trigger for feature branches

env:
  MAIN_BRANCH: main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]  # Test on multiple Node.js versions
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test

  create-pr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}   # The current feature branch
          base: ${{ env.MAIN_BRANCH }}       # Target branch (main)
          title: "Auto PR: Merge ${GITHUB_REF#refs/heads/} into main"
          body: "This PR was automatically created after successful tests on the feature branch."
          draft: false

  auto-merge:
    needs: create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Pull Request
        uses: peter-evans/merge-pull-request@v2
        with:
          merge-method: squash
          github-token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: [test, create-pr, auto-merge]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack of Merge Success
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          fields: repo,message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify Slack of Merge Failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
